- package.json
- pages/index.tsx
- yarn.lock
> :zap: Implement lazy loading

- TODO.md
We need help. Here is a non-exhaustive list of tasks on which dev & non-dev ppl can help.
> 📝 Add TODO list for community participation

- README.md
- TODO.md
- next.config.js
- src/assets/locales/it.ts
- src/assets/locales/pl.ts
- src/assets/locales/pt.ts
- src/assets/locales/zh_CN.ts
- src/assets/locales/zh_TW.ts
- src/components/layout/Header.tsx
- src/context/TranslateProvider/provider.tsx
- Add Polski and Portugez translations
- Update README
> :sparkles: Add PL & PT translations | Update README

- data/ecosystem.ts
Removes unwanted tags in zkx project
> 🎨 Updating ZKX

- data/ecosystem.ts
> Add ZKasino no logo

- src/pages/metrics/index.tsx
Replace argent-x specific lib by get-starknet
> :globe_with_meridians: Replace lib

- data/ecosystem.ts
Almanac just launched on mainnet.
I'm updating the description and providing a link to the contract.
> 🎨 Updating AlmanacNFT

- data/ecosystem.ts
> :add Carbonable

- data/ecosystem.ts
https://twitter.com/Carbonable_io
> update carboanble twitter

- data/job.ts
The job offer is no longer valid.
Small note: I'm not sure, whether to update the "key" of following job description.
> Dropping Carmine Options job offer

- data/ecosystem.ts
Update discord link of StarkSport
> 🎨 Updating StarkSport

- README.md
- docs/add-job.md
- docs/add-project.md
- docs/translations.md
- docs/update-job.md
- docs/update-project.md
> Fix: typos

- data/ecosystem.ts
Update the website link of Stark Sport.
> 🎨 Updating Stark Sport

- README.md
- data/academy.ts
- data/ecosystem.ts
- data/job.ts
- next-seo.config.js
- src/assets/locales/en.ts
- src/assets/locales/fr.ts
- src/assets/locales/it.ts
- src/assets/locales/pl.ts
- src/assets/locales/pt.ts
- src/assets/locales/tr.ts
- src/assets/locales/zh_CN.ts
- src/assets/locales/zh_TW.ts
- src/components/academy/ContributeContent.tsx
- src/components/academy/NewsInfosContent.tsx
- src/pages/academy/index.tsx
- src/services/project.service.spec.ts
Changes the spelling of "StarkNet" from "StarkNet" to "Starknet" everywhere in the doc and code following the recommendations in [this SNIP](https://community.starknet.io/t/snip-naming-convention-starknet-not-starknet).
> Change the spelling of "StarkNet" to "Starknet"

- .github/script/src/sync-data.ts
Changed the letter case of the image
> :construction_worker: Call refresh twitter banners in CI

- data/ecosystem.ts
> 🎨 Updating Jediswap

- data/ecosystem.ts
A one-stop gateway of Defi provides real-time price charts and trading data analysis across multi-chains and Dexs that integrates many utility tools, including watchlist, DeFi portfolio tracker, notebook, price alert etc.
Now, we have integrated StarkNet mainnet for making all users to track all tokens trends on StartkNet
> ✨ Introducing WEChart

- data/ecosystem.ts
Updates Carmine's entry as we're now live on Mainnet and have a Medium account.
> ✨ Update Carmine Finance entry

- data/academy.ts
Change docs references to the updated one
> ref: updates docs references

- data/ecosystem.ts
> ✨ Updating Fibrous

- data/ecosystem.ts
- data/job.ts
> ⚡️Updating RN Bridge Details & Adding new Jobs⚡️

- data/ecosystem.ts
Influence is live on mainnet now (ref: https://voyager.online/contract/0x0422d33a3638dcc4c62e72e1d6942cd31eb643ef596ccac2351e0e21f6cd4bf4)
- updated description
- updated discrod
- added github
> Updated Influence info for live on mainnet

- data/job.ts
Hello
I fixed some typos that i found
1. Coding knowledge and experience **is** required-----------Coding knowledge and experience **are** required
2. contacts - contracts
3. responsability - responsibility 
Hope it helps.
> Fix Typo in data/job.ts

- data/ecosystem.ts
Modif: - Bountive discord link
- islive true
> ✨ Introducing Bountive

- data/ecosystem.ts
> 🎨 Updating Metacube

- src/assets/locales/it.ts
> locales it

- src/assets/locales/zh_TW.ts
> Added zh_tw language key

- src/assets/locales/fr.ts
> docs: added french keys

- data/ecosystem.ts
> 🎨 Updating StakingRewards

- data/ecosystem.ts
Updated Layerswap description and added Telegram link
> Update Layerswap info in ecosystem.ts
